bf16: true
cutoff_len: 6144
dataset: sentence_reorganizer_train
dataset_dir: data
do_train: true
enable_liger_kernel: true
eval_accumulation_steps: 8
eval_dataset: sentence_reorganizer_val
eval_steps: 20
eval_strategy: steps
finetuning_type: lora
flash_attn: fa2
fp16: false
gradient_accumulation_steps: 8
hub_model_id: VerbACxSS/sempl-it-sentence-reorganizer
learning_rate: 2.0e-05
logging_steps: 5
logging_strategy: steps
lora_alpha: 16
lora_dropout: 0.05
lora_rank: 64
lora_target: q_proj,v_proj
loraplus_lr_ratio: 1
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 1020
model_name_or_path: unsloth/Qwen2.5-7B-Instruct-bnb-4bit
num_train_epochs: 5.0
output_dir: output/sentence-reorganizer
overwrite_cache: true
overwrite_output_dir: true
packing: false
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: tensorboard
save_strategy: epoch
stage: sft
template: qwen
use_dora: false
use_rslora: false
warmup_ratio: 0.1
